### ISSUE TITLE
breaker for "XmlSecurity.4624.windows.xml" does not work

### ISSUE THREAD

**Issue by abeeber** [my2ndhead/TA-microsoft-windows#1]
Hi, I'm trying to generate some 4624 events. I am not getting any results for the sample file "XmlSecurity.4624.windows.xml". Eventgen provides an error that the breaker is invalid and is reverting to the default.

Any suggestions in resolving this?

**Comment by my2ndhead** [comment]
Hmm, not sure why this happens. The Sample file is copied straight from the Splunk_TA_windows add-on.

Can you try to copy it from that add-on? Maybe there's a character set problem etc.

**Comment by abeeber** [comment]
Yeah, the problem is buried there too. David Maislin helped me troubleshoot it. The problem is the regex for the breaker variable. It does not work for any of the XmlSecurity.XXXX.windows.xml samples.

We ended up using:
[XmlSecurity\.[0-9]*\.windows\.xml]
index = wineventlog
source = WinEventLog:Security
interval = 60
sourcetype = XmlWinEventLog:Security
breaker = [^\r\n\s]+

[XmlSystem.update_.*\.xml]
index = wineventlog
source = WinEventLog:System
sourcetype = XmlWinEventLog:System
breaker = [^\r\n\s]+

The default breaker works.
